// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: blocks.proto
// Protobuf Java Version: 4.35.0

package org.delaunois.ialon.blocks.protobuf;

@com.google.protobuf.Generated
public final class BlocksProtos extends com.google.protobuf.GeneratedFile {
  private BlocksProtos() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "BlocksProtos");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChunkProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChunkProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
     * </pre>
     *
     * <code>repeated sint32 location = 1 [packed = true];</code>
     * @return A list containing the location.
     */
    java.util.List<java.lang.Integer> getLocationList();
    /**
     * <pre>
     * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
     * </pre>
     *
     * <code>repeated sint32 location = 1 [packed = true];</code>
     * @return The count of location.
     */
    int getLocationCount();
    /**
     * <pre>
     * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
     * </pre>
     *
     * <code>repeated sint32 location = 1 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The location at the given index.
     */
    int getLocation(int index);

    /**
     * <pre>
     * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
     * </pre>
     *
     * <code>repeated sint32 size = 2 [packed = true];</code>
     * @return A list containing the size.
     */
    java.util.List<java.lang.Integer> getSizeList();
    /**
     * <pre>
     * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
     * </pre>
     *
     * <code>repeated sint32 size = 2 [packed = true];</code>
     * @return The count of size.
     */
    int getSizeCount();
    /**
     * <pre>
     * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
     * </pre>
     *
     * <code>repeated sint32 size = 2 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The size at the given index.
     */
    int getSize(int index);

    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     * @return A list containing the blocks.
     */
    java.util.List<java.lang.String>
        getBlocksList();
    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     * @return The count of blocks.
     */
    int getBlocksCount();
    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     * @param index The index of the element to return.
     * @return The blocks at the given index.
     */
    java.lang.String getBlocks(int index);
    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the blocks at the given index.
     */
    com.google.protobuf.ByteString
        getBlocksBytes(int index);

    /**
     * <pre>
     * the lightmap array
     * </pre>
     *
     * <code>bytes lightmap = 4;</code>
     * @return The lightmap.
     */
    com.google.protobuf.ByteString getLightmap();
  }
  /**
   * Protobuf type {@code ChunkProto}
   */
  public static final class ChunkProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ChunkProto)
      ChunkProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 0,
        /* suffix= */ "",
        "ChunkProto");
    }
    // Use ChunkProto.newBuilder() to construct.
    private ChunkProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ChunkProto() {
      location_ = emptyIntList();
      size_ = emptyIntList();
      blocks_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      lightmap_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.delaunois.ialon.blocks.protobuf.BlocksProtos.internal_static_ChunkProto_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return org.delaunois.ialon.blocks.protobuf.BlocksProtos.internal_static_ChunkProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.delaunois.ialon.blocks.protobuf.BlocksProtos.internal_static_ChunkProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto.class, org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto.Builder.class);
    }

    public static final int LOCATION_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList location_ =
        emptyIntList();
    /**
     * <pre>
     * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
     * </pre>
     *
     * <code>repeated sint32 location = 1 [packed = true];</code>
     * @return A list containing the location.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getLocationList() {
      return location_;
    }
    /**
     * <pre>
     * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
     * </pre>
     *
     * <code>repeated sint32 location = 1 [packed = true];</code>
     * @return The count of location.
     */
    public int getLocationCount() {
      return location_.size();
    }
    /**
     * <pre>
     * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
     * </pre>
     *
     * <code>repeated sint32 location = 1 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The location at the given index.
     */
    public int getLocation(int index) {
      return location_.getInt(index);
    }
    private int locationMemoizedSerializedSize = -1;

    public static final int SIZE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList size_ =
        emptyIntList();
    /**
     * <pre>
     * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
     * </pre>
     *
     * <code>repeated sint32 size = 2 [packed = true];</code>
     * @return A list containing the size.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getSizeList() {
      return size_;
    }
    /**
     * <pre>
     * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
     * </pre>
     *
     * <code>repeated sint32 size = 2 [packed = true];</code>
     * @return The count of size.
     */
    public int getSizeCount() {
      return size_.size();
    }
    /**
     * <pre>
     * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
     * </pre>
     *
     * <code>repeated sint32 size = 2 [packed = true];</code>
     * @param index The index of the element to return.
     * @return The size at the given index.
     */
    public int getSize(int index) {
      return size_.getInt(index);
    }
    private int sizeMemoizedSerializedSize = -1;

    public static final int BLOCKS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList blocks_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     * @return A list containing the blocks.
     */
    public com.google.protobuf.ProtocolStringList
        getBlocksList() {
      return blocks_;
    }
    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     * @return The count of blocks.
     */
    public int getBlocksCount() {
      return blocks_.size();
    }
    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     * @param index The index of the element to return.
     * @return The blocks at the given index.
     */
    public java.lang.String getBlocks(int index) {
      return blocks_.get(index);
    }
    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the blocks at the given index.
     */
    public com.google.protobuf.ByteString
        getBlocksBytes(int index) {
      return blocks_.getByteString(index);
    }

    public static final int LIGHTMAP_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString lightmap_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * the lightmap array
     * </pre>
     *
     * <code>bytes lightmap = 4;</code>
     * @return The lightmap.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLightmap() {
      return lightmap_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getLocationList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(locationMemoizedSerializedSize);
      }
      for (int i = 0; i < location_.size(); i++) {
        output.writeSInt32NoTag(location_.getInt(i));
      }
      if (getSizeList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(sizeMemoizedSerializedSize);
      }
      for (int i = 0; i < size_.size(); i++) {
        output.writeSInt32NoTag(size_.getInt(i));
      }
      for (int i = 0; i < blocks_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, blocks_.getRaw(i));
      }
      if (!lightmap_.isEmpty()) {
        output.writeBytes(4, lightmap_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < location_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeSInt32SizeNoTag(location_.getInt(i));
        }
        size += dataSize;
        if (!getLocationList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        locationMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < size_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeSInt32SizeNoTag(size_.getInt(i));
        }
        size += dataSize;
        if (!getSizeList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        sizeMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < blocks_.size(); i++) {
          dataSize += computeStringSizeNoTag(blocks_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getBlocksList().size();
      }
      if (!lightmap_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, lightmap_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto)) {
        return super.equals(obj);
      }
      org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto other = (org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto) obj;

      if (!getLocationList()
          .equals(other.getLocationList())) return false;
      if (!getSizeList()
          .equals(other.getSizeList())) return false;
      if (!getBlocksList()
          .equals(other.getBlocksList())) return false;
      if (!getLightmap()
          .equals(other.getLightmap())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLocationCount() > 0) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocationList().hashCode();
      }
      if (getSizeCount() > 0) {
        hash = (37 * hash) + SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getSizeList().hashCode();
      }
      if (getBlocksCount() > 0) {
        hash = (37 * hash) + BLOCKS_FIELD_NUMBER;
        hash = (53 * hash) + getBlocksList().hashCode();
      }
      hash = (37 * hash) + LIGHTMAP_FIELD_NUMBER;
      hash = (53 * hash) + getLightmap().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChunkProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChunkProto)
        org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.delaunois.ialon.blocks.protobuf.BlocksProtos.internal_static_ChunkProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.delaunois.ialon.blocks.protobuf.BlocksProtos.internal_static_ChunkProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto.class, org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto.Builder.class);
      }

      // Construct using org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        location_ = emptyIntList();
        size_ = emptyIntList();
        blocks_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        lightmap_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.delaunois.ialon.blocks.protobuf.BlocksProtos.internal_static_ChunkProto_descriptor;
      }

      @java.lang.Override
      public org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto getDefaultInstanceForType() {
        return org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto.getDefaultInstance();
      }

      @java.lang.Override
      public org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto build() {
        org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto buildPartial() {
        org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto result = new org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          location_.makeImmutable();
          result.location_ = location_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          size_.makeImmutable();
          result.size_ = size_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          blocks_.makeImmutable();
          result.blocks_ = blocks_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.lightmap_ = lightmap_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto) {
          return mergeFrom((org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto other) {
        if (other == org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto.getDefaultInstance()) return this;
        if (!other.location_.isEmpty()) {
          if (location_.isEmpty()) {
            location_ = other.location_;
            location_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureLocationIsMutable();
            location_.addAll(other.location_);
          }
          onChanged();
        }
        if (!other.size_.isEmpty()) {
          if (size_.isEmpty()) {
            size_ = other.size_;
            size_.makeImmutable();
            bitField0_ |= 0x00000002;
          } else {
            ensureSizeIsMutable();
            size_.addAll(other.size_);
          }
          onChanged();
        }
        if (!other.blocks_.isEmpty()) {
          if (blocks_.isEmpty()) {
            blocks_ = other.blocks_;
            bitField0_ |= 0x00000004;
          } else {
            ensureBlocksIsMutable();
            blocks_.addAll(other.blocks_);
          }
          onChanged();
        }
        if (!other.getLightmap().isEmpty()) {
          setLightmap(other.getLightmap());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int v = input.readSInt32();
                ensureLocationIsMutable();
                location_.addInt(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureLocationIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  location_.addInt(input.readSInt32());
                }
                input.popLimit(limit);
                break;
              } // case 10
              case 16: {
                int v = input.readSInt32();
                ensureSizeIsMutable();
                size_.addInt(v);
                break;
              } // case 16
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureSizeIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  size_.addInt(input.readSInt32());
                }
                input.popLimit(limit);
                break;
              } // case 18
              case 26: {
                ensureBlocksIsMutable();
                blocks_.add(input.readStringRequireUtf8());
                break;
              } // case 26
              case 34: {
                lightmap_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList location_ = emptyIntList();
      private void ensureLocationIsMutable() {
        if (!location_.isModifiable()) {
          location_ = makeMutableCopy(location_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <pre>
       * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
       * </pre>
       *
       * <code>repeated sint32 location = 1 [packed = true];</code>
       * @return A list containing the location.
       */
      public java.util.List<java.lang.Integer>
          getLocationList() {
        location_.makeImmutable();
        return location_;
      }
      /**
       * <pre>
       * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
       * </pre>
       *
       * <code>repeated sint32 location = 1 [packed = true];</code>
       * @return The count of location.
       */
      public int getLocationCount() {
        return location_.size();
      }
      /**
       * <pre>
       * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
       * </pre>
       *
       * <code>repeated sint32 location = 1 [packed = true];</code>
       * @param index The index of the element to return.
       * @return The location at the given index.
       */
      public int getLocation(int index) {
        return location_.getInt(index);
      }
      /**
       * <pre>
       * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
       * </pre>
       *
       * <code>repeated sint32 location = 1 [packed = true];</code>
       * @param index The index to set the value at.
       * @param value The location to set.
       * @return This builder for chaining.
       */
      public Builder setLocation(
          int index, int value) {

        ensureLocationIsMutable();
        location_.setInt(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
       * </pre>
       *
       * <code>repeated sint32 location = 1 [packed = true];</code>
       * @param value The location to add.
       * @return This builder for chaining.
       */
      public Builder addLocation(int value) {

        ensureLocationIsMutable();
        location_.addInt(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
       * </pre>
       *
       * <code>repeated sint32 location = 1 [packed = true];</code>
       * @param values The location to add.
       * @return This builder for chaining.
       */
      public Builder addAllLocation(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureLocationIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, location_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
       * </pre>
       *
       * <code>repeated sint32 location = 1 [packed = true];</code>
       * @return This builder for chaining.
       */
      public Builder clearLocation() {
        location_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList size_ = emptyIntList();
      private void ensureSizeIsMutable() {
        if (!size_.isModifiable()) {
          size_ = makeMutableCopy(size_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <pre>
       * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
       * </pre>
       *
       * <code>repeated sint32 size = 2 [packed = true];</code>
       * @return A list containing the size.
       */
      public java.util.List<java.lang.Integer>
          getSizeList() {
        size_.makeImmutable();
        return size_;
      }
      /**
       * <pre>
       * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
       * </pre>
       *
       * <code>repeated sint32 size = 2 [packed = true];</code>
       * @return The count of size.
       */
      public int getSizeCount() {
        return size_.size();
      }
      /**
       * <pre>
       * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
       * </pre>
       *
       * <code>repeated sint32 size = 2 [packed = true];</code>
       * @param index The index of the element to return.
       * @return The size at the given index.
       */
      public int getSize(int index) {
        return size_.getInt(index);
      }
      /**
       * <pre>
       * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
       * </pre>
       *
       * <code>repeated sint32 size = 2 [packed = true];</code>
       * @param index The index to set the value at.
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(
          int index, int value) {

        ensureSizeIsMutable();
        size_.setInt(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
       * </pre>
       *
       * <code>repeated sint32 size = 2 [packed = true];</code>
       * @param value The size to add.
       * @return This builder for chaining.
       */
      public Builder addSize(int value) {

        ensureSizeIsMutable();
        size_.addInt(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
       * </pre>
       *
       * <code>repeated sint32 size = 2 [packed = true];</code>
       * @param values The size to add.
       * @return This builder for chaining.
       */
      public Builder addAllSize(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSizeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, size_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
       * </pre>
       *
       * <code>repeated sint32 size = 2 [packed = true];</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        size_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList blocks_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureBlocksIsMutable() {
        if (!blocks_.isModifiable()) {
          blocks_ = new com.google.protobuf.LazyStringArrayList(blocks_);
        }
        bitField0_ |= 0x00000004;
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       * @return A list containing the blocks.
       */
      public com.google.protobuf.ProtocolStringList
          getBlocksList() {
        blocks_.makeImmutable();
        return blocks_;
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       * @return The count of blocks.
       */
      public int getBlocksCount() {
        return blocks_.size();
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       * @param index The index of the element to return.
       * @return The blocks at the given index.
       */
      public java.lang.String getBlocks(int index) {
        return blocks_.get(index);
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the blocks at the given index.
       */
      public com.google.protobuf.ByteString
          getBlocksBytes(int index) {
        return blocks_.getByteString(index);
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       * @param index The index to set the value at.
       * @param value The blocks to set.
       * @return This builder for chaining.
       */
      public Builder setBlocks(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureBlocksIsMutable();
        blocks_.set(index, value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       * @param value The blocks to add.
       * @return This builder for chaining.
       */
      public Builder addBlocks(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureBlocksIsMutable();
        blocks_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       * @param values The blocks to add.
       * @return This builder for chaining.
       */
      public Builder addAllBlocks(
          java.lang.Iterable<java.lang.String> values) {
        ensureBlocksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blocks_);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlocks() {
        blocks_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       * @param value The bytes of the blocks to add.
       * @return This builder for chaining.
       */
      public Builder addBlocksBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureBlocksIsMutable();
        blocks_.add(value);
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString lightmap_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * the lightmap array
       * </pre>
       *
       * <code>bytes lightmap = 4;</code>
       * @return The lightmap.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getLightmap() {
        return lightmap_;
      }
      /**
       * <pre>
       * the lightmap array
       * </pre>
       *
       * <code>bytes lightmap = 4;</code>
       * @param value The lightmap to set.
       * @return This builder for chaining.
       */
      public Builder setLightmap(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        lightmap_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the lightmap array
       * </pre>
       *
       * <code>bytes lightmap = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLightmap() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lightmap_ = getDefaultInstance().getLightmap();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ChunkProto)
    }

    // @@protoc_insertion_point(class_scope:ChunkProto)
    private static final org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto();
    }

    public static org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChunkProto>
        PARSER = new com.google.protobuf.AbstractParser<ChunkProto>() {
      @java.lang.Override
      public ChunkProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChunkProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChunkProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.delaunois.ialon.blocks.protobuf.BlocksProtos.ChunkProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChunkProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChunkProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014blocks.proto\"V\n\nChunkProto\022\024\n\010location" +
      "\030\001 \003(\021B\002\020\001\022\020\n\004size\030\002 \003(\021B\002\020\001\022\016\n\006blocks\030\003" +
      " \003(\t\022\020\n\010lightmap\030\004 \001(\014B3\n#org.delaunois." +
      "ialon.blocks.protobufB\014BlocksProtosb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ChunkProto_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_ChunkProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ChunkProto_descriptor,
        new java.lang.String[] { "Location", "Size", "Blocks", "Lightmap", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
