// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blocks.proto

package org.delaunois.ialon.protobuf;

public final class BlocksProtos {
  private BlocksProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChunkProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChunkProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
     * </pre>
     *
     * <code>repeated sint32 location = 1 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getLocationList();
    /**
     * <pre>
     * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
     * </pre>
     *
     * <code>repeated sint32 location = 1 [packed = true];</code>
     */
    int getLocationCount();
    /**
     * <pre>
     * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
     * </pre>
     *
     * <code>repeated sint32 location = 1 [packed = true];</code>
     */
    int getLocation(int index);

    /**
     * <pre>
     * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
     * </pre>
     *
     * <code>repeated sint32 size = 2 [packed = true];</code>
     */
    java.util.List<java.lang.Integer> getSizeList();
    /**
     * <pre>
     * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
     * </pre>
     *
     * <code>repeated sint32 size = 2 [packed = true];</code>
     */
    int getSizeCount();
    /**
     * <pre>
     * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
     * </pre>
     *
     * <code>repeated sint32 size = 2 [packed = true];</code>
     */
    int getSize(int index);

    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     */
    java.util.List<java.lang.String>
        getBlocksList();
    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     */
    int getBlocksCount();
    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     */
    java.lang.String getBlocks(int index);
    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     */
    com.google.protobuf.ByteString
        getBlocksBytes(int index);

    /**
     * <pre>
     * the lightmap array
     * </pre>
     *
     * <code>bytes lightmap = 4;</code>
     */
    com.google.protobuf.ByteString getLightmap();
  }
  /**
   * Protobuf type {@code ChunkProto}
   */
  public  static final class ChunkProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChunkProto)
      ChunkProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChunkProto.newBuilder() to construct.
    private ChunkProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChunkProto() {
      location_ = java.util.Collections.emptyList();
      size_ = java.util.Collections.emptyList();
      blocks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      lightmap_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChunkProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                location_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              location_.add(input.readSInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                location_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                location_.add(input.readSInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                size_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              size_.add(input.readSInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                size_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                size_.add(input.readSInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                blocks_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              blocks_.add(s);
              break;
            }
            case 34: {

              lightmap_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          location_ = java.util.Collections.unmodifiableList(location_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          size_ = java.util.Collections.unmodifiableList(size_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          blocks_ = blocks_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.delaunois.ialon.protobuf.BlocksProtos.internal_static_ChunkProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.delaunois.ialon.protobuf.BlocksProtos.internal_static_ChunkProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto.class, org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto.Builder.class);
    }

    private int bitField0_;
    public static final int LOCATION_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> location_;
    /**
     * <pre>
     * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
     * </pre>
     *
     * <code>repeated sint32 location = 1 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getLocationList() {
      return location_;
    }
    /**
     * <pre>
     * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
     * </pre>
     *
     * <code>repeated sint32 location = 1 [packed = true];</code>
     */
    public int getLocationCount() {
      return location_.size();
    }
    /**
     * <pre>
     * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
     * </pre>
     *
     * <code>repeated sint32 location = 1 [packed = true];</code>
     */
    public int getLocation(int index) {
      return location_.get(index);
    }
    private int locationMemoizedSerializedSize = -1;

    public static final int SIZE_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> size_;
    /**
     * <pre>
     * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
     * </pre>
     *
     * <code>repeated sint32 size = 2 [packed = true];</code>
     */
    public java.util.List<java.lang.Integer>
        getSizeList() {
      return size_;
    }
    /**
     * <pre>
     * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
     * </pre>
     *
     * <code>repeated sint32 size = 2 [packed = true];</code>
     */
    public int getSizeCount() {
      return size_.size();
    }
    /**
     * <pre>
     * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
     * </pre>
     *
     * <code>repeated sint32 size = 2 [packed = true];</code>
     */
    public int getSize(int index) {
      return size_.get(index);
    }
    private int sizeMemoizedSerializedSize = -1;

    public static final int BLOCKS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList blocks_;
    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getBlocksList() {
      return blocks_;
    }
    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     */
    public int getBlocksCount() {
      return blocks_.size();
    }
    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     */
    public java.lang.String getBlocks(int index) {
      return blocks_.get(index);
    }
    /**
     * <pre>
     * the block array
     * </pre>
     *
     * <code>repeated string blocks = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBlocksBytes(int index) {
      return blocks_.getByteString(index);
    }

    public static final int LIGHTMAP_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString lightmap_;
    /**
     * <pre>
     * the lightmap array
     * </pre>
     *
     * <code>bytes lightmap = 4;</code>
     */
    public com.google.protobuf.ByteString getLightmap() {
      return lightmap_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getLocationList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(locationMemoizedSerializedSize);
      }
      for (int i = 0; i < location_.size(); i++) {
        output.writeSInt32NoTag(location_.get(i));
      }
      if (getSizeList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(sizeMemoizedSerializedSize);
      }
      for (int i = 0; i < size_.size(); i++) {
        output.writeSInt32NoTag(size_.get(i));
      }
      for (int i = 0; i < blocks_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, blocks_.getRaw(i));
      }
      if (!lightmap_.isEmpty()) {
        output.writeBytes(4, lightmap_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < location_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeSInt32SizeNoTag(location_.get(i));
        }
        size += dataSize;
        if (!getLocationList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        locationMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < size_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeSInt32SizeNoTag(size_.get(i));
        }
        size += dataSize;
        if (!getSizeList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        sizeMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < blocks_.size(); i++) {
          dataSize += computeStringSizeNoTag(blocks_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getBlocksList().size();
      }
      if (!lightmap_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, lightmap_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto)) {
        return super.equals(obj);
      }
      org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto other = (org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto) obj;

      boolean result = true;
      result = result && getLocationList()
          .equals(other.getLocationList());
      result = result && getSizeList()
          .equals(other.getSizeList());
      result = result && getBlocksList()
          .equals(other.getBlocksList());
      result = result && getLightmap()
          .equals(other.getLightmap());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLocationCount() > 0) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocationList().hashCode();
      }
      if (getSizeCount() > 0) {
        hash = (37 * hash) + SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getSizeList().hashCode();
      }
      if (getBlocksCount() > 0) {
        hash = (37 * hash) + BLOCKS_FIELD_NUMBER;
        hash = (53 * hash) + getBlocksList().hashCode();
      }
      hash = (37 * hash) + LIGHTMAP_FIELD_NUMBER;
      hash = (53 * hash) + getLightmap().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChunkProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChunkProto)
        org.delaunois.ialon.protobuf.BlocksProtos.ChunkProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.delaunois.ialon.protobuf.BlocksProtos.internal_static_ChunkProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.delaunois.ialon.protobuf.BlocksProtos.internal_static_ChunkProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto.class, org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto.Builder.class);
      }

      // Construct using org.delaunois.explore.gamelogic.protobuf.BlocksProtos.ChunkProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        location_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        size_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        blocks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        lightmap_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.delaunois.ialon.protobuf.BlocksProtos.internal_static_ChunkProto_descriptor;
      }

      @java.lang.Override
      public org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto getDefaultInstanceForType() {
        return org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto.getDefaultInstance();
      }

      @java.lang.Override
      public org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto build() {
        org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto buildPartial() {
        org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto result = new org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          location_ = java.util.Collections.unmodifiableList(location_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.location_ = location_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size_ = java.util.Collections.unmodifiableList(size_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.size_ = size_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          blocks_ = blocks_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.blocks_ = blocks_;
        result.lightmap_ = lightmap_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto) {
          return mergeFrom((org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto other) {
        if (other == org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto.getDefaultInstance()) return this;
        if (!other.location_.isEmpty()) {
          if (location_.isEmpty()) {
            location_ = other.location_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLocationIsMutable();
            location_.addAll(other.location_);
          }
          onChanged();
        }
        if (!other.size_.isEmpty()) {
          if (size_.isEmpty()) {
            size_ = other.size_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSizeIsMutable();
            size_.addAll(other.size_);
          }
          onChanged();
        }
        if (!other.blocks_.isEmpty()) {
          if (blocks_.isEmpty()) {
            blocks_ = other.blocks_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureBlocksIsMutable();
            blocks_.addAll(other.blocks_);
          }
          onChanged();
        }
        if (other.getLightmap() != com.google.protobuf.ByteString.EMPTY) {
          setLightmap(other.getLightmap());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> location_ = java.util.Collections.emptyList();
      private void ensureLocationIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          location_ = new java.util.ArrayList<java.lang.Integer>(location_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
       * </pre>
       *
       * <code>repeated sint32 location = 1 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getLocationList() {
        return java.util.Collections.unmodifiableList(location_);
      }
      /**
       * <pre>
       * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
       * </pre>
       *
       * <code>repeated sint32 location = 1 [packed = true];</code>
       */
      public int getLocationCount() {
        return location_.size();
      }
      /**
       * <pre>
       * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
       * </pre>
       *
       * <code>repeated sint32 location = 1 [packed = true];</code>
       */
      public int getLocation(int index) {
        return location_.get(index);
      }
      /**
       * <pre>
       * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
       * </pre>
       *
       * <code>repeated sint32 location = 1 [packed = true];</code>
       */
      public Builder setLocation(
          int index, int value) {
        ensureLocationIsMutable();
        location_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
       * </pre>
       *
       * <code>repeated sint32 location = 1 [packed = true];</code>
       */
      public Builder addLocation(int value) {
        ensureLocationIsMutable();
        location_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
       * </pre>
       *
       * <code>repeated sint32 location = 1 [packed = true];</code>
       */
      public Builder addAllLocation(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureLocationIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, location_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the location of the chunk, represented as an array of 3 integers. Where location[0] = x, location[1] = y, location[2] = z
       * </pre>
       *
       * <code>repeated sint32 location = 1 [packed = true];</code>
       */
      public Builder clearLocation() {
        location_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> size_ = java.util.Collections.emptyList();
      private void ensureSizeIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          size_ = new java.util.ArrayList<java.lang.Integer>(size_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
       * </pre>
       *
       * <code>repeated sint32 size = 2 [packed = true];</code>
       */
      public java.util.List<java.lang.Integer>
          getSizeList() {
        return java.util.Collections.unmodifiableList(size_);
      }
      /**
       * <pre>
       * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
       * </pre>
       *
       * <code>repeated sint32 size = 2 [packed = true];</code>
       */
      public int getSizeCount() {
        return size_.size();
      }
      /**
       * <pre>
       * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
       * </pre>
       *
       * <code>repeated sint32 size = 2 [packed = true];</code>
       */
      public int getSize(int index) {
        return size_.get(index);
      }
      /**
       * <pre>
       * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
       * </pre>
       *
       * <code>repeated sint32 size = 2 [packed = true];</code>
       */
      public Builder setSize(
          int index, int value) {
        ensureSizeIsMutable();
        size_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
       * </pre>
       *
       * <code>repeated sint32 size = 2 [packed = true];</code>
       */
      public Builder addSize(int value) {
        ensureSizeIsMutable();
        size_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
       * </pre>
       *
       * <code>repeated sint32 size = 2 [packed = true];</code>
       */
      public Builder addAllSize(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureSizeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, size_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the size of the chunk, represented as an array of 3 integers. where size[0] = x, size[1] = y, size[2] = z
       * </pre>
       *
       * <code>repeated sint32 size = 2 [packed = true];</code>
       */
      public Builder clearSize() {
        size_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList blocks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureBlocksIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          blocks_ = new com.google.protobuf.LazyStringArrayList(blocks_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getBlocksList() {
        return blocks_.getUnmodifiableView();
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       */
      public int getBlocksCount() {
        return blocks_.size();
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       */
      public java.lang.String getBlocks(int index) {
        return blocks_.get(index);
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBlocksBytes(int index) {
        return blocks_.getByteString(index);
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       */
      public Builder setBlocks(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBlocksIsMutable();
        blocks_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       */
      public Builder addBlocks(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureBlocksIsMutable();
        blocks_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       */
      public Builder addAllBlocks(
          java.lang.Iterable<java.lang.String> values) {
        ensureBlocksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blocks_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       */
      public Builder clearBlocks() {
        blocks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the block array
       * </pre>
       *
       * <code>repeated string blocks = 3;</code>
       */
      public Builder addBlocksBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureBlocksIsMutable();
        blocks_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString lightmap_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * the lightmap array
       * </pre>
       *
       * <code>bytes lightmap = 4;</code>
       */
      public com.google.protobuf.ByteString getLightmap() {
        return lightmap_;
      }
      /**
       * <pre>
       * the lightmap array
       * </pre>
       *
       * <code>bytes lightmap = 4;</code>
       */
      public Builder setLightmap(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lightmap_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the lightmap array
       * </pre>
       *
       * <code>bytes lightmap = 4;</code>
       */
      public Builder clearLightmap() {
        
        lightmap_ = getDefaultInstance().getLightmap();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChunkProto)
    }

    // @@protoc_insertion_point(class_scope:ChunkProto)
    private static final org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto();
    }

    public static org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChunkProto>
        PARSER = new com.google.protobuf.AbstractParser<ChunkProto>() {
      @java.lang.Override
      public ChunkProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChunkProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChunkProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChunkProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.delaunois.ialon.protobuf.BlocksProtos.ChunkProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChunkProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChunkProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014blocks.proto\"V\n\nChunkProto\022\024\n\010location" +
      "\030\001 \003(\021B\002\020\001\022\020\n\004size\030\002 \003(\021B\002\020\001\022\016\n\006blocks\030\003" +
      " \003(\t\022\020\n\010lightmap\030\004 \001(\014B/\n\037org.delaunois." +
      "explorer.protobufB\014BlocksProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ChunkProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChunkProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChunkProto_descriptor,
        new java.lang.String[] { "Location", "Size", "Blocks", "Lightmap", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
