package org.delaunois.ialon;

import com.jme3.asset.DesktopAssetManager;
import com.jme3.util.BufferAllocatorFactory;
import com.jme3.util.PrimitiveAllocator;
import org.delaunois.ialon.blocks.BlocksConfig;
import org.delaunois.ialon.blocks.Chunk;
import com.simsilica.mathd.Vec3i;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.delaunois.ialon.blocks.WorldEditOverlay;
import org.delaunois.ialon.blocks.generator.NoiseTerrainGenerator;

/**
 * Validates that the per-column heightmap memorization in {@link NoiseTerrainGenerator} does not
 * change the generated terrain : a chunk generated with a warm (column-shared) cache must be
 * byte-identical to the same chunk generated by a fresh generator with a cold cache.
 */
class NoiseTerrainGeneratorTest {

    static {
        System.setProperty(BufferAllocatorFactory.PROPERTY_BUFFER_ALLOCATOR_IMPLEMENTATION, PrimitiveAllocator.class.getName());
    }

    @BeforeAll
    static void setUp() {
        IalonInitializer.configureBlocksFramework(new DesktopAssetManager(true), new IalonConfig());
    }

    @Test
    void columnHeightMemorizationProducesIdenticalChunks() {
        float waterHeight = new IalonConfig().getWaterHeight();
        int gridHeight = new IalonConfig().getGridHeight();

        // One generator that memorizes the heightmap across the whole vertical column.
        NoiseTerrainGenerator shared = new NoiseTerrainGenerator(2, waterHeight);

        for (int x = -1; x <= 1; x++) {
            for (int z = -1; z <= 1; z++) {
                for (int y = 0; y < gridHeight; y++) {
                    Vec3i loc = new Vec3i(x, y, z);
                    // After y == 0 of a column, this hits the memorized heightmap.
                    Chunk warm = shared.generate(loc);

                    // Cold reference : a brand-new generator recomputes the heightmap from scratch.
                    Chunk cold = new NoiseTerrainGenerator(2, waterHeight).generate(loc);

                    assertArrayEquals(cold.getBlocks(), warm.getBlocks(),
                            "blocks differ for chunk " + loc);
                    assertArrayEquals(cold.getLightMap(), warm.getLightMap(),
                            "lightmap differs for chunk " + loc);
                }
            }
        }
    }

    /**
     * On the finite torus, vegetation (trees + decorative grass) must be as seamless as the terrain :
     * the forest-density map is tiled and the per-cell tree scatter + per-column grass wrap exactly at
     * the period. So a chunk and its twin one full period (W) away in X must be byte-identical.
     */
    @Test
    void vegetationIsSeamlessAcrossTheTorusSeam() {
        IalonConfig config = new IalonConfig();
        float w = config.getWorldSize(); // 4096 by default (finite world)
        int gridHeight = config.getGridHeight();
        int chunksPerPeriod = (int) (w / BlocksConfig.getInstance().getChunkSize().x);

        NoiseTerrainGenerator gen =
                new NoiseTerrainGenerator(2, config.getWaterHeight(), config.getMaxy(), w);

        for (int y = 0; y < gridHeight; y++) {
            Chunk a = gen.generate(new Vec3i(0, y, 0));
            Chunk b = gen.generate(new Vec3i(chunksPerPeriod, y, 0));
            assertArrayEquals(a.getBlocks(), b.getBlocks(),
                    "vegetation/terrain must match across the +W seam at y=" + y);
        }
    }

    /**
     * The minimap's "modified column" key must wrap to the world period on the torus (so an edit shows in
     * every copy of a tile, recorded once) and stay raw on an infinite world.
     */
    @Test
    void modifiedColumnKeyWrapsToTheTorusPeriod() {
        IalonConfig config = new IalonConfig();
        float w = config.getWorldSize(); // 4096 (finite)
        int across = (int) (w / BlocksConfig.getInstance().getChunkSize().x);
        NoiseTerrainGenerator torus =
                new NoiseTerrainGenerator(2, config.getWaterHeight(), config.getMaxy(), w);

        // A column and its twin one full period away collapse to the same canonical key.
        assertEquals(torus.modifiedColumnKey(3, -5),
                torus.modifiedColumnKey(3 + across, -5 + 2 * across));
        // Canonical coordinates are wrapped into [0, across).
        long key = torus.modifiedColumnKey(-1, across);
        assertEquals(across - 1, WorldEditOverlay.unpackX(key));
        assertEquals(0, WorldEditOverlay.unpackZ(key));

        // Infinite world (worldSize 0) : no wrapping, raw coordinates preserved.
        NoiseTerrainGenerator infinite = new NoiseTerrainGenerator(2, config.getWaterHeight());
        long raw = infinite.modifiedColumnKey(-7, 9);
        assertEquals(-7, WorldEditOverlay.unpackX(raw));
        assertEquals(9, WorldEditOverlay.unpackZ(raw));
    }

    /**
     * Multi-world non-regression : the new tunable generation knobs default to the original constants,
     * so a generator left at its defaults must produce byte-identical terrain to the pre-refactor one.
     */
    @Test
    void defaultKnobsLeaveTerrainUnchanged() {
        float waterHeight = new IalonConfig().getWaterHeight();
        int gridHeight = new IalonConfig().getGridHeight();

        NoiseTerrainGenerator base = new NoiseTerrainGenerator(2, waterHeight);
        NoiseTerrainGenerator knobbed = new NoiseTerrainGenerator(2, waterHeight);
        knobbed.setReliefAmplitude(1f);
        knobbed.setReliefFrequency(1f);
        knobbed.setTreeMaxProb(knobbed.getTreeMaxProb());
        knobbed.setForestFrequency(knobbed.getForestFrequency());

        for (int x = -1; x <= 1; x++) {
            for (int z = -1; z <= 1; z++) {
                for (int y = 0; y < gridHeight; y++) {
                    Vec3i loc = new Vec3i(x, y, z);
                    assertArrayEquals(base.generate(loc).getBlocks(), knobbed.generate(loc).getBlocks(),
                            "default knobs must not change blocks for chunk " + loc);
                }
            }
        }
    }

    /**
     * Lowering the water level must only drain the basins, NOT sink the whole terrain : the hard floor
     * (the lowland shelf) is decoupled from waterHeight. So the terrain heights at waterHeight 0 are
     * identical to those at the default 30, and waterHeight 0 yields no water block at all.
     */
    @Test
    void lowWaterDrainsBasinsWithoutSinkingTerrain() {
        IalonConfig config = new IalonConfig();
        NoiseTerrainGenerator wh30 = new NoiseTerrainGenerator(2, 30f, config.getMaxy(), config.getWorldSize());
        NoiseTerrainGenerator wh0 = new NoiseTerrainGenerator(2, 0f, config.getMaxy(), config.getWorldSize());

        // Terrain shape is unchanged by the water level : the per-column heights match exactly.
        com.jme3.math.Vector3f p = new com.jme3.math.Vector3f();
        for (int wx = -2048; wx < 2048; wx += 64) {
            for (int wz = -2048; wz < 2048; wz += 64) {
                org.junit.jupiter.api.Assertions.assertEquals(
                        wh30.getHeight(p.set(wx, 0, wz)), wh0.getHeight(p.set(wx, 0, wz)), 0.001f,
                        "terrain height must not depend on waterHeight at (" + wx + "," + wz + ")");
            }
        }

        // And no water block is generated at waterHeight 0.
        org.delaunois.ialon.blocks.BlockRegistry reg = BlocksConfig.getInstance().getBlockRegistry();
        short waterSourceId = reg.get(org.delaunois.ialon.blocks.BlockIds.WATER_SOURCE).getId();
        short waterLiquidId = reg.get(org.delaunois.ialon.blocks.BlockIds.getName(
                org.delaunois.ialon.blocks.BlockIds.WATER, org.delaunois.ialon.blocks.ShapeIds.LIQUID)).getId();
        for (int x = -6; x <= 6; x++) {
            for (int z = -6; z <= 6; z++) {
                for (int y = 0; y < config.getGridHeight(); y++) {
                    short[] blocks = wh0.generate(new Vec3i(x, y, z)).getBlocks();
                    if (blocks == null) continue; // empty (air-only) chunk
                    for (short id : blocks) {
                        org.junit.jupiter.api.Assertions.assertTrue(id != waterSourceId && id != waterLiquidId,
                                "no water expected at waterHeight=0");
                    }
                }
            }
        }
    }

    /**
     * The soft ceiling must keep even max-relief peaks under the world ceiling (gridHeight*chunkHeight),
     * so they round off instead of being flat-cut at the top of the chunk grid.
     */
    @Test
    void maxReliefPeaksStayUnderCeiling() {
        IalonConfig config = new IalonConfig();
        int ceiling = config.getMaxy();
        NoiseTerrainGenerator gen = new NoiseTerrainGenerator(2, 30f, ceiling, config.getWorldSize());
        gen.setReliefAmplitude(2.5f); // slider max
        com.jme3.math.Vector3f p = new com.jme3.math.Vector3f();
        for (int wx = -2048; wx < 2048; wx += 8) {
            for (int wz = -2048; wz < 2048; wz += 8) {
                float h = gen.getHeight(p.set(wx, 0, wz));
                org.junit.jupiter.api.Assertions.assertTrue(h <= ceiling - 2f,
                        "peak height " + h + " must stay under the ceiling " + ceiling + " at (" + wx + "," + wz + ")");
            }
        }
    }

    /**
     * Trees must be rooted in the ground, never floating : the trunk base must read its column height from
     * the same slot the surface fill uses (heights[2 + index]). A mismatch made trees float 1 block on
     * slopes. Scans a wide area and asserts no trunk has an air gap below its lowest log.
     */
    @Test
    void treesAreNeverFloating() {
        IalonConfig config = new IalonConfig();
        int ch = config.getChunkHeight();
        int gh = config.getGridHeight();
        int chunkSize = BlocksConfig.getInstance().getChunkSize().x;
        int colH = ch * gh;

        org.delaunois.ialon.blocks.BlockRegistry reg = BlocksConfig.getInstance().getBlockRegistry();
        java.util.Set<Short> logIds = new java.util.HashSet<>();
        for (String n : new String[]{org.delaunois.ialon.blocks.BlockIds.OAK_LOG, org.delaunois.ialon.blocks.BlockIds.BIRCH_LOG,
                org.delaunois.ialon.blocks.BlockIds.SPRUCE_LOG, org.delaunois.ialon.blocks.BlockIds.PALM_TREE_LOG}) {
            logIds.add(reg.get(n).getId());
        }

        NoiseTerrainGenerator gen = new NoiseTerrainGenerator(2, 30f, config.getMaxy(), config.getWorldSize());
        int trees = 0;
        int span = 16;
        for (int cx = -span; cx <= span; cx++) {
            for (int cz = -span; cz <= span; cz++) {
                Chunk[] col = new Chunk[gh];
                for (int cy = 0; cy < gh; cy++) col[cy] = gen.generate(new Vec3i(cx, cy, cz));
                for (int lx = 0; lx < chunkSize; lx++) {
                    for (int lz = 0; lz < chunkSize; lz++) {
                        int lowestLog = -1;
                        for (int wy = 0; wy < colH && lowestLog < 0; wy++) {
                            org.delaunois.ialon.blocks.Block b = col[wy / ch].getBlock(lx, wy % ch, lz);
                            if (b != null && logIds.contains(b.getId())) lowestLog = wy;
                        }
                        if (lowestLog < 0) continue;
                        trees++;
                        // The block directly below the trunk base must be solid (the surface) -- not air.
                        org.delaunois.ialon.blocks.Block below = lowestLog > 0
                                ? col[(lowestLog - 1) / ch].getBlock(lx, (lowestLog - 1) % ch, lz) : null;
                        org.junit.jupiter.api.Assertions.assertNotNull(below,
                                "floating tree (air below trunk base) at world(" + (cx * chunkSize + lx)
                                        + "," + (cz * chunkSize + lz) + ") base=" + lowestLog);
                    }
                }
            }
        }
        org.junit.jupiter.api.Assertions.assertTrue(trees > 100, "expected many trees in the scanned area, got " + trees);
    }

    /**
     * The relief amplitude knob must actually reshape the terrain : doubling it changes the heightmap.
     */
    @Test
    void reliefAmplitudeChangesTerrain() {
        float waterHeight = new IalonConfig().getWaterHeight();
        NoiseTerrainGenerator standard = new NoiseTerrainGenerator(2, waterHeight);
        NoiseTerrainGenerator amplified = new NoiseTerrainGenerator(2, waterHeight);
        amplified.setReliefAmplitude(2f);

        float standardTotal = 0f;
        float amplifiedTotal = 0f;
        for (int i = 0; i < 64; i++) {
            com.jme3.math.Vector3f p = new com.jme3.math.Vector3f(i * 13f, 0, i * 7f);
            standardTotal += standard.getHeight(p);
            amplifiedTotal += amplified.getHeight(p);
        }
        org.junit.jupiter.api.Assertions.assertNotEquals(standardTotal, amplifiedTotal,
                "doubling reliefAmplitude must change the terrain height");
    }
}
