package org.delaunois.ialon;

import com.jme3.asset.DesktopAssetManager;
import com.jme3.util.BufferAllocatorFactory;
import com.jme3.util.PrimitiveAllocator;
import org.delaunois.ialon.blocks.BlocksConfig;
import org.delaunois.ialon.blocks.Chunk;
import com.simsilica.mathd.Vec3i;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import org.delaunois.ialon.blocks.generator.NoiseTerrainGenerator;

/**
 * Validates that the per-column heightmap memorization in {@link NoiseTerrainGenerator} does not
 * change the generated terrain : a chunk generated with a warm (column-shared) cache must be
 * byte-identical to the same chunk generated by a fresh generator with a cold cache.
 */
class NoiseTerrainGeneratorTest {

    static {
        System.setProperty(BufferAllocatorFactory.PROPERTY_BUFFER_ALLOCATOR_IMPLEMENTATION, PrimitiveAllocator.class.getName());
    }

    @BeforeAll
    static void setUp() {
        IalonInitializer.configureBlocksFramework(new DesktopAssetManager(true), new IalonConfig());
    }

    @Test
    void columnHeightMemorizationProducesIdenticalChunks() {
        float waterHeight = new IalonConfig().getWaterHeight();
        int gridHeight = new IalonConfig().getGridHeight();

        // One generator that memorizes the heightmap across the whole vertical column.
        NoiseTerrainGenerator shared = new NoiseTerrainGenerator(2, waterHeight);

        for (int x = -1; x <= 1; x++) {
            for (int z = -1; z <= 1; z++) {
                for (int y = 0; y < gridHeight; y++) {
                    Vec3i loc = new Vec3i(x, y, z);
                    // After y == 0 of a column, this hits the memorized heightmap.
                    Chunk warm = shared.generate(loc);

                    // Cold reference : a brand-new generator recomputes the heightmap from scratch.
                    Chunk cold = new NoiseTerrainGenerator(2, waterHeight).generate(loc);

                    assertArrayEquals(cold.getBlocks(), warm.getBlocks(),
                            "blocks differ for chunk " + loc);
                    assertArrayEquals(cold.getLightMap(), warm.getLightMap(),
                            "lightmap differs for chunk " + loc);
                }
            }
        }
    }

    /**
     * On the finite torus, vegetation (trees + decorative grass) must be as seamless as the terrain :
     * the forest-density map is tiled and the per-cell tree scatter + per-column grass wrap exactly at
     * the period. So a chunk and its twin one full period (W) away in X must be byte-identical.
     */
    @Test
    void vegetationIsSeamlessAcrossTheTorusSeam() {
        IalonConfig config = new IalonConfig();
        float w = config.getWorldSize(); // 4096 by default (finite world)
        int gridHeight = config.getGridHeight();
        int chunksPerPeriod = (int) (w / BlocksConfig.getInstance().getChunkSize().x);

        NoiseTerrainGenerator gen =
                new NoiseTerrainGenerator(2, config.getWaterHeight(), config.getMaxy(), w);

        for (int y = 0; y < gridHeight; y++) {
            Chunk a = gen.generate(new Vec3i(0, y, 0));
            Chunk b = gen.generate(new Vec3i(chunksPerPeriod, y, 0));
            assertArrayEquals(a.getBlocks(), b.getBlocks(),
                    "vegetation/terrain must match across the +W seam at y=" + y);
        }
    }

    /**
     * Multi-world non-regression : the new tunable generation knobs default to the original constants,
     * so a generator left at its defaults must produce byte-identical terrain to the pre-refactor one.
     */
    @Test
    void defaultKnobsLeaveTerrainUnchanged() {
        float waterHeight = new IalonConfig().getWaterHeight();
        int gridHeight = new IalonConfig().getGridHeight();

        NoiseTerrainGenerator base = new NoiseTerrainGenerator(2, waterHeight);
        NoiseTerrainGenerator knobbed = new NoiseTerrainGenerator(2, waterHeight);
        knobbed.setReliefAmplitude(1f);
        knobbed.setReliefFrequency(1f);
        knobbed.setTreeMaxProb(knobbed.getTreeMaxProb());
        knobbed.setForestFrequency(knobbed.getForestFrequency());

        for (int x = -1; x <= 1; x++) {
            for (int z = -1; z <= 1; z++) {
                for (int y = 0; y < gridHeight; y++) {
                    Vec3i loc = new Vec3i(x, y, z);
                    assertArrayEquals(base.generate(loc).getBlocks(), knobbed.generate(loc).getBlocks(),
                            "default knobs must not change blocks for chunk " + loc);
                }
            }
        }
    }

    /**
     * The relief amplitude knob must actually reshape the terrain : doubling it changes the heightmap.
     */
    @Test
    void reliefAmplitudeChangesTerrain() {
        float waterHeight = new IalonConfig().getWaterHeight();
        NoiseTerrainGenerator standard = new NoiseTerrainGenerator(2, waterHeight);
        NoiseTerrainGenerator amplified = new NoiseTerrainGenerator(2, waterHeight);
        amplified.setReliefAmplitude(2f);

        float standardTotal = 0f;
        float amplifiedTotal = 0f;
        for (int i = 0; i < 64; i++) {
            com.jme3.math.Vector3f p = new com.jme3.math.Vector3f(i * 13f, 0, i * 7f);
            standardTotal += standard.getHeight(p);
            amplifiedTotal += amplified.getHeight(p);
        }
        org.junit.jupiter.api.Assertions.assertNotEquals(standardTotal, amplifiedTotal,
                "doubling reliefAmplitude must change the terrain height");
    }
}
